[build]
  command = "npm run build"
  publish = ".next"          # Carpeta de build de Next.js
  functions = "netlify/functions"  # Carpeta donde Netlify pone las funciones serverless

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirecciones para manejar rutas antiguas
[[redirects]]
  from = "/productos"
  to = "/categoria/todos"
  status = 301
  force = true

[[redirects]]
  from = "/productos/*"
  to = "/product/:splat"
  status = 301
  force = true

